KTU_Proje_SourceCode/KTU_Proje/Controllers/PanelimController.cs
using KTU_Proje.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTU_Proje.Controllers
{
    public class PanelimController : Controller
    {
        StudentIDEntities db = new StudentIDEntities();

        // GET: Panelim
        [HttpGet]

        public ActionResult Index()
        {


            var uyemail = (string)Session["Mail"];
            //var degerler = db.TBL_UYELER.FirstOrDefault(z => z.MAIL == uyemail);
            var degerler = db.TBL_STUDENT.ToList();
            var d1 = db.TBL_STUDENT.Where(x => x.MAIL == uyemail).Select(y => y.AD).FirstOrDefault();
            ViewBag.d1 = d1;
            var d2 = db.TBL_STUDENT.Where(x => x.MAIL == uyemail).Select(y => y.SOYAD).FirstOrDefault();
            ViewBag.d2 = d2;

            var d5 = db.TBL_STUDENT.Where(x => x.MAIL == uyemail).Select(y => y.OKUL).FirstOrDefault();
            ViewBag.d5 = d5;
            var d6 = db.TBL_STUDENT.Where(x => x.MAIL == uyemail).Select(y => y.TELEFON).FirstOrDefault();
            ViewBag.d6 = d6;
            var d7 = db.TBL_STUDENT.Where(x => x.MAIL == uyemail).Select(y => y.MAIL).FirstOrDefault();
            ViewBag.d7 = d7;
            var uyeid = db.TBL_STUDENT.Where(x => x.MAIL == uyemail).Select(y => y.ID).FirstOrDefault();


            return View(degerler);


        }
        [HttpPost]
        public ActionResult Index2(TBL_STUDENT u)
        {


            var kullanici = (string)Session["Mail"];
            var uye = db.TBL_STUDENT.FirstOrDefault(x => x.MAIL == kullanici);
            uye.SIFRE = u.SIFRE;
            uye.AD = u.AD;
            uye.SOYAD = u.SOYAD;
            uye.MAIL = u.MAIL;
            uye.OKUL = u.OKUL;
            uye.OGRENCIBELGESI = u.OGRENCIBELGESI;
            db.SaveChanges();
            return RedirectToAction("Index");


        }

        public PartialViewResult Partial1()
        {
            var kullanici2 = (string)Session["Mail"];
            var id = db.TBL_STUDENT.Where(x => x.MAIL == kullanici2).Select(y => y.ID).FirstOrDefault();
            var uyebul = db.TBL_STUDENT.Find(id);
            return PartialView("Partial1", uyebul);
        }

    }
}

KTU_Proje_SourceCode/KTU_Proje/Views/Panelim/Index.cshtml
@using KTU_Proje.Models
@model List<TBL_STUDENT>

@{
    Layout = null;
}


@{

    ViewBag.Title = "Index";



}



<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Üye Paneli</title>



    <meta name="viewport" content="width=device-width, initial-scale=1">



    <!-- Font Awesome -->

    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body class="hold-transition sidebar-mini">

    <!-- Navbar -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->

    <section class="content-header">

        <div class="container-fluid">

            <div class="row mb-2">

                <div class="col-sm-6">

                    <h1>Profilim</h1>

                </div>



            </div>

        </div><!-- /.container-fluid -->

    </section>



    <!-- Main content -->

    <section class="content">

        <div class="container-fluid">

            <div class="row">

                <div class="col-md-3">



                    <!-- Profile Image -->

                    <div class="card card-primary card-outline">

                        <div class="card-body box-profile">





                            <h3 class="profile-username text-center">@ViewBag.d1 @ViewBag.d2 </h3>



                            <p class="text-muted text-center">Kütüphane Üyesi</p>







                            <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a>

                        </div>

                        <!-- /.card-body -->

                    </div>

                    <!-- /.card -->
                    <!-- About Me Box -->

                    <div class="card card-primary">

                        <div class="card-header">

                            <h3 class="card-title">Hakkımda</h3>

                        </div>

                        <!-- /.card-header -->

                        <div class="card-body">

                            <strong><i class="fas fa-book mr-1"></i> Okul</strong>



                            <p class="text-muted">

                                @ViewBag.d5

                            </p>



                            <hr>



                            <strong><i class="fas fa-phone-alt mr-1"></i> Telefon</strong>



                            <p class="text-muted">@ViewBag.d6</p>



                            <hr>



                            <strong><i class="fas fa-pencil-alt mr-1"></i> Kullanıcı Adı</strong>



                            <p class="text-muted">

                                @ViewBag.d4

                            </p>



                            <hr>



                            <strong><i class="far fa-file-alt mr-1"></i> Mail Adresi</strong>



                            <p class="text-muted">@ViewBag.d7</p>

                        </div>

                        <!-- /.card-body -->

                    </div>

                    <!-- /.card -->

                </div>

                <!-- /.col -->

                <div class="col-md-9">

                    <div class="card">

                        <div class="card-header p-2">

                            <ul class="nav nav-pills">




                                <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Ayarlar</a></li>

                            </ul>

                        </div><!-- /.card-header -->

                        <div class="card-body">

                            <div class="tab-content">

                                <div class="active tab-pane" id="activity">

                                    <!-- Post -->
                                    

                                    @Html.Action("Partial1", "Panelim")


                                    





                                    <!-- /.post -->

                                </div>





                                <!-- /.tab-pane -->

                            </div>

                            <!-- /.tab-content -->

                        </div><!-- /.card-body -->

                    </div>

                    <!-- /.nav-tabs-custom -->

                </div>

                <!-- /.col -->

            </div>

            <!-- /.row -->

        </div><!-- /.container-fluid -->

    </section>

    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->

    <aside class="control-sidebar control-sidebar-dark">

        <!-- Control sidebar content goes here -->

    </aside>

    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="../../plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="../../dist/js/adminlte.min.js"></script>

    <!-- AdminLTE for demo purposes -->

    <script src="../../dist/js/demo.js"></script>

</body>

</html>

KTU_Proje_SourceCode/KTU_Proje/Views/Panelim/Partial1.cshtml
@model KTU_Proje.Models.TBL_STUDENT
@using (Html.BeginForm("Index2", "Panelim", FormMethod.Post))

{<form class="form-horizontal">

        <div class="form-group row">

            <label for="inputName" class="col-sm-2 col-form-label">Ad</label>

            <div class="col-sm-10">

                @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })

            </div>

        </div>

        <div class="form-group row">

            <label for="inputName" class="col-sm-2 col-form-label">Soyad</label>

            <div class="col-sm-10">

                @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control" })

            </div>

        </div>


        <div class="form-group row">

            <label for="inputName" class="col-sm-2 col-form-label">Şifre</label>

            <div class="col-sm-10">

                @Html.TextBoxFor(x => x.SIFRE, new { @class = "form-control" })

            </div>

        </div>



        <div class="form-group row">

            <label for="inputName" class="col-sm-2 col-form-label">Okul</label>

            <div class="col-sm-10">

                @Html.TextBoxFor(x => x.OKUL, new { @class = "form-control" })

            </div>

        </div>


        <div class="form-group row">

            <label for="inputName" class="col-sm-2 col-form-label">Öğrenci Belgesi</label>

            <div class="col-sm-10">

                @Html.TextBoxFor(x => x.OGRENCIBELGESI, new { @class = "form-control" })

            </div>

        </div>
        <div class="form-group row">

            <div class="offset-sm-2 col-sm-10">

                <div class="checkbox">

                    <label>

                        <input type="checkbox"> Şartları okudum <a href="https://www.mevzuat.gov.tr/mevzuat?MevzuatNo=6698&MevzuatTur=1&MevzuatTertip=5">kabul ediyorum</a>

                    </label>

                </div>

            </div>

        </div>

        <div class="form-group row">

            <div class="offset-sm-2 col-sm-10">

                <button type="submit" class="btn btn-danger">Güncelle</button>

            </div>

        </div>

    </form>}